### ISSUE TITLE
showdam causing segfault

### ISSUE THREAD

**Issue by fourty7** [rotjmud/issues#8]
Here's the stacktrace:

```sh
#0  0xf727597c in __mempcpy_ia32 () from /lib/libc.so.6
#1  0xf7267a14 in __GI__IO_default_xsputn () from /lib/libc.so.6
#2  0xf723aff3 in vfprintf () from /lib/libc.so.6
#3  0xf725b732 in vsprintf () from /lib/libc.so.6
#4  0xf724069f in sprintf () from /lib/libc.so.6
#5  0x081b664c in act_with_dam (str=0x83731f8 "tiny bits and pieces with $s %s#w.", hide_invisible=0, ch=0xc65ced8, obj=0x0, vict_obj=0x11f6ab40, type=6,
    dam=10, did_crit=17 '\021') at comm.c:3275
#6  0x0806d7b4 in dam_message (dam=10, ch=0xc65ced8, victim=0x11f6ab40, did_crit=0 '\000', w_type=312, input_message=0x8456934 <damage_messages+180>)
    at combat/dam_message.c:29
#7  0x08076f89 in damage_crit (ch=0xc65ced8, victim=0x11f6ab40, crit=0 '\000', dam=10, attacktype=312, special=0, fight_starter=1 '\001',
    message=0x8456934 <damage_messages+180>) at combat/damage.c:914
#8  0x0807143d in hit (ch=0xc65ced8, victim=0x11f6ab40, type=-1) at combat/hit.c:452
#9  0x0809f990 in handle_npc_attacks (ch=0xc65ced8, vict=0x11f6ab40) at pulses/perform_violence.c:1113
#10 0x080a04e7 in perform_violence () at pulses/perform_violence.c:1349
#11 0x081ac023 in heartbeat (pulse=334800) at comm.c:1034
#12 0x081abdd5 in game_loop (mother_desc=3) at comm.c:946
#13 0x081aa8ed in init_game (port=9400) at comm.c:484
#14 0x081aa333 in main (argc=2, argv=0xffd99634) at comm.c:312
```

Here's the core filename: core.tmp.26397

**Comment by fourty7** [comment]
Thamael's screenshot:

![image](https://cdn.discordapp.com/attachments/647509183335366695/779788520179892234/unknown.png)
